spring:
  datasource:
    schemata:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost/information_schema?characterEncoding=utf-8&useSSL=false
    mock:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost/yxpay_ci?characterEncoding=utf-8&useSSL=false
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

mybatis:
  mapper:
    mock: classpath:mybatis/mapper/mock/*.xml
    schemata: classpath:mybatis/mapper/schemata/*.xml
logging:
  config: classpath:log/logging-config.xml
server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
