spring:
  datasource:
    schemata:
      driverClassName: com.mysql.jdbc.Driver
      username: yunxi
      password: yunxi
      url: jdbc:mysql://192.168.33.11/information_schema?characterEncoding=utf-8&useSSL=false
    mock:
      driverClassName: com.mysql.jdbc.Driver
      username: yunxi
      password: yunxi
      url: jdbc:mysql://192.168.33.11/yxpay_ci?characterEncoding=utf-8&useSSL=false
mybatis:
  mapper:
    mock: classpath:mybatis/mapper/mock/*.xml
    schemata: classpath:mybatis/mapper/schemata/*.xml
logging:
  config: classpath:log/logging-config.xml
default:
  annotation:
    entity: {Data}
    table: {Table,Entity,Data}
    colummn: {Id,Column}
name:
  rule:
    entity: $Eo
    url: main\java\
server:
  port: 8091
